/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermsImport } from './routes/terms'
import { Route as IndexImport } from './routes/index'
import { Route as ChatChatImport } from './routes/chat/_chat'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthSigninImport } from './routes/auth/signin'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'
import { Route as ChatChatIndexImport } from './routes/chat/_chat.index'

// Create Virtual Routes

const ChatImport = createFileRoute('/chat')()

// Create/Update Routes

const ChatRoute = ChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const TermsRoute = TermsImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChatChatRoute = ChatChatImport.update({
  id: '/_chat',
  getParentRoute: () => ChatRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const ChatChatIndexRoute = ChatChatIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatChatRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/chat/_chat': {
      id: '/chat/_chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatChatImport
      parentRoute: typeof ChatRoute
    }
    '/chat/_chat/': {
      id: '/chat/_chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatChatIndexImport
      parentRoute: typeof ChatChatImport
    }
  }
}

// Create and export the route tree

interface ChatChatRouteChildren {
  ChatChatIndexRoute: typeof ChatChatIndexRoute
}

const ChatChatRouteChildren: ChatChatRouteChildren = {
  ChatChatIndexRoute: ChatChatIndexRoute,
}

const ChatChatRouteWithChildren = ChatChatRoute._addFileChildren(
  ChatChatRouteChildren,
)

interface ChatRouteChildren {
  ChatChatRoute: typeof ChatChatRouteWithChildren
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatRoute: ChatChatRouteWithChildren,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/chat': typeof ChatChatRouteWithChildren
  '/chat/': typeof ChatChatIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/chat': typeof ChatChatIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/chat': typeof ChatRouteWithChildren
  '/chat/_chat': typeof ChatChatRouteWithChildren
  '/chat/_chat/': typeof ChatChatIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/chat'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/chat'
    | '/chat/_chat'
    | '/chat/_chat/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TermsRoute: typeof TermsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ChatRoute: typeof ChatRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TermsRoute: TermsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  ChatRoute: ChatRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/terms",
        "/auth/forgot-password",
        "/auth/signin",
        "/auth/signup",
        "/chat"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/terms": {
      "filePath": "terms.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/signin": {
      "filePath": "auth/signin.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/chat": {
      "filePath": "chat",
      "children": [
        "/chat/_chat"
      ]
    },
    "/chat/_chat": {
      "filePath": "chat/_chat.tsx",
      "parent": "/chat",
      "children": [
        "/chat/_chat/"
      ]
    },
    "/chat/_chat/": {
      "filePath": "chat/_chat.index.tsx",
      "parent": "/chat/_chat"
    }
  }
}
ROUTE_MANIFEST_END */
